### ISSUE TITLE
Py4JJavaError 

### ISSUE THREAD

**Issue by midannii** [koalanlp/python-support#11]
### 기초정보
- Python 버전이 얼마입니까?
  - [ ] 3.5.x
  - [ ] 3.6.x
  - [ O ] 3.7.x (jupyter lab)
- KoalaNLP 버전이 얼마인가요?
  - [ ] 1.x
  - [ O ] 2.x
- 문제의 유형은 어떤 것인가요?
  - [ O ] 버그리포트
  - [ ] 개선점제안
  - [ ] 사용법질문
  - [ ] 기타

### 재연을 위한 정보
- 어떤 문장을 시도하셨습니까?
```text
충돌과 폭발 등 극단상황에 대한 발주자 또는 건축주의 특별한 요구가 있는 경우에는 이를 고려하여 설계하여야 한다.
```
또한, 
```text
내구성능검증에서 복합열화를 무시할 수 없을 경우에는 이를 고려하여야 한다.
```
- KoalaNLP를 사용한 코드 부분을 보여주세요.
```python
from koalanlp.Util import initialize, finalize
from koalanlp import API
from koalanlp.proc import Parser

initialize(hnn='LATEST')
parser = Parser(API.HNN)
parsed = parser(sentence) # sentence에 해당 문장을 입력했음 
```

### 본문
- 아래와 같은 에러 메세지가 발생하여 등록합니다. 

```
[root] Java에서 처리하던 중에 문제가 발생했습니다. 문제가 계속된다면, Issue를 등록해주세요.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/koalanlp/proc.py", line 213, in analyze
    result += py_list(self.__api.analyze(string(paragraph)), item_converter=Sentence.fromJava)
  File "/opt/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/anaconda3/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o209.analyze.
: java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at kaist.cilab.parser.corpusconverter.sejong2treebank.sejongtree.NonterminalNode.readPennInformation(NonterminalNode.java:98)
	at kaist.cilab.parser.corpusconverter.sejong2treebank.sejongtree.ParseTree.<init>(ParseTree.java:57)
	at kr.bydelta.koala.hnn.Parser.parseTreeOf(proc.kt:512)
	at kr.bydelta.koala.hnn.Parser.attachProperty(proc.kt:492)
	at kr.bydelta.koala.hnn.Parser.attachProperty(proc.kt:376)
	at kr.bydelta.koala.proc.CanAnalyzeProperty$DefaultImpls.analyze(processors.kt:625)
	at kr.bydelta.koala.proc.CanParseDependency$DefaultImpls.analyze(processors.kt)
	at kr.bydelta.koala.hnn.Parser.analyze(proc.kt:376)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by nearbydelta** [comment]
좀 많이 늦어서 죄송합니다.
혹시 자바 버전이나 OS 정보를 알 수 있을까요?
